import type { Counted, ExtractionResult } from "./extract";

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) return "_None detected._\n";
  const lines = [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((r) => `| ${r.map((c) => c.replace(/\|/g, "\\|")).join(" | ")} |`),
  ];
  return lines.join("\n") + "\n";
}

function code(v: string): string {
  return `\`${v.replace(/`/g, "'")}\``;
}

function countedRows(items: Counted[]): string[][] {
  return items.map((i) => [code(i.value), String(i.count)]);
}

export function generateDesignMd(r: ExtractionResult): string {
  const sections: string[] = [];

  sections.push(`# DESIGN.md

> Design system reference extracted from [${r.title}](${r.url})
> Generated by DESIGN.md Lab on ${r.fetchedAt.slice(0, 10)} · static CSS analysis (${r.stylesheetCount} stylesheet${r.stylesheetCount === 1 ? "" : "s"}, ${r.inlineStyleBlocks} inline style block${r.inlineStyleBlocks === 1 ? "" : "s"}, ${(r.cssBytes / 1024).toFixed(0)} KB of CSS)

## Overview

- **Source:** ${r.url}
- **Page title:** ${r.title}${r.description ? `\n- **Description:** ${r.description}` : ""}${r.generator ? `\n- **Generator:** ${r.generator}` : ""}${r.themeColor ? `\n- **Theme color:** ${code(r.themeColor)}` : ""}

This document describes the visual language of the source site so an AI coding agent can reproduce its look and feel. Values are ordered by how often they appear in the site's CSS — treat high-frequency values as the core scale and rare ones as exceptions.
`);

  if (r.customProperties.length > 0) {
    sections.push(`## Design tokens (CSS custom properties)

The site defines its own token layer. Prefer these variables over hard-coded values when recreating components.

${table(
  ["Token", "Uses"],
  r.customProperties.map((c) => {
    const [name, ...rest] = c.value.split(": ");
    return [`${code(name)} → ${code(rest.join(": ") || "—")}`, String(c.count)];
  }),
)}`);
  }

  sections.push(`## Color palette

Most-used colors across text, backgrounds, borders, and shadows. The top entries define the core palette; use them for primary surfaces and text.

${table(["Color", "Occurrences"], countedRows(r.colors))}`);

  sections.push(`## Typography

### Font families

${table(["Family", "Occurrences"], countedRows(r.fontFamilies))}
### Type scale (font sizes)

${table(["Size", "Occurrences"], countedRows(r.fontSizes))}
### Font weights

${table(["Weight", "Occurrences"], countedRows(r.fontWeights))}
### Line heights

${table(["Line height", "Occurrences"], countedRows(r.lineHeights))}${
    r.letterSpacings.length
      ? `
### Letter spacing

${table(["Letter spacing", "Occurrences"], countedRows(r.letterSpacings))}`
      : ""
  }`);

  sections.push(`## Spacing scale

Margin, padding, and gap values by frequency. The recurring values below form the site's effective spacing scale.

${table(["Value", "Occurrences"], countedRows(r.spacing))}`);

  sections.push(`## Corners & elevation

### Border radius

${table(["Radius", "Occurrences"], countedRows(r.radii))}
### Shadows

${table(["Shadow", "Occurrences"], countedRows(r.shadows))}`);

  if (r.transitions.length > 0 || r.zIndices.length > 0) {
    sections.push(`## Motion & layering
${
      r.transitions.length
        ? `
### Transitions

${table(["Transition", "Occurrences"], countedRows(r.transitions))}`
        : ""
    }${
      r.zIndices.length
        ? `
### Z-index layers

${table(["z-index", "Occurrences"], countedRows(r.zIndices))}`
        : ""
    }`);
  }

  if (r.components.length > 0) {
    const componentSections = r.components
      .map((c) => {
        const rows = Object.entries(c.declarations).map(([prop, value]) => [code(prop), code(value)]);
        return `### ${c.name}

Selectors seen: ${c.selectors.map(code).join(", ")}

${table(["Property", "Most common value"], rows)}`;
      })
      .join("\n");
    sections.push(`## Components

Best-effort styles recovered from common selectors. Values shown are the most frequent declaration for each property.

${componentSections}`);
  }

  sections.push(`## Notes for agents

- Values were extracted **statically** from shipped CSS; styles injected at runtime by JavaScript are not captured.
- Frequency counts include all matched rules, so utility-heavy sites (e.g. Tailwind) surface their generated scale rather than hand-written tokens.
- When recreating this design: start from the custom-property token layer if present, then the top 3–5 colors, the two most common font families, and the recurring spacing steps.
${r.warnings.length ? `\n### Extraction warnings\n\n${r.warnings.map((w) => `- ${w}`).join("\n")}\n` : ""}`);

  return sections.join("\n");
}
